on: workflow_dispatch

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with latest upstream

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: docs

    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.2
      with:
        upstream_repository: 'Kapeli/Dash-User-Contributions'
        upstream_branch: 'master'
        target_branch: 'docs'

    - name: Timestamp
      run: date

  build_docs:
    runs-on: ubuntu-latest
    container: kraklin/elm-docset:1.1.0
    steps:
      - run: 'ls -la /usr/src/app'
      - run: 'cd /usr/src/app'
      - run: 'echo $PWD && ls -la'
